# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'a4it' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for a4it 

pod 'Firebase/Core'
pod 'Firebase/Database'

  target 'a4itTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'a4itUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
