# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'A4IT' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod 'Firebase/Core'
	pod 'Firebase/Messaging'
  # Pods for A4IT

  target 'A4ITTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'A4ITUITests' do
    inherit! :search_paths
    # Pods for testing


  end

end
